#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=5:00
#PBS -A open

# Get started
echo "Job started on `hostname` at `date`"

# Load in default gcc module
module purge
module load gcc

# Go to the correct place
cd $PBS_O_WORKDIR

# Run the job itself
#    compile and produce executable
g++ matmult.cpp -o matmult
#    run executable with necessary input arguments (matrix dims - outer, inner, outer)
./matmult 1000 1200 1000

# Finish up
echo "Job Ended at `date`"
