#PBS -l nodes=1:ppn=2
#PBS -l walltime=3:00:00
#PBS -l pmem=2gb
#PBS -A open
#PBS -j oe
# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load in module
module load mathematica
echo "mathematica is loaded"
# Go to the correct place
cd $PBS_O_WORKDIR
echo "loaded to the pwd"
# Run the job
math -script Example.nb


# Finish up
echo " "
echo "Job Ended at `date`"
echo " "
