#!/bin/bash
#PBS -l nodes=1:ppn=2
#PBS -l pmem=2gb
#PBS -l walltime=10:00
#PBS -A open

# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load modules and set environment
module load schrodinger/2016.4
export SCHRODINGER_TMPDIR="~/scratch"

# cd to the submission directory
cd $PBS_O_WORKDIR

# Run maestro
/opt/aci/sw/schrodinger/2016.4/glide glide-dock_SP_8.in -OVERWRITE -NJOBS 2 -HOST localhost:2 -WAIT -NONICE
