#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=8:00:00
#PBS -l pmem=12gb
#PBS -A open
#PBS -N sm_${max}_${st}

# Get started
echo "Job started on `hostname` at `date`"

# Load in matlab
module purge
module load gcc

# Go to the correct place
cd $PBS_O_WORKDIR

# Run the job itself - a matlab script called runThis.m
g++ stalinmerge_sort.cpp -o sm_${max}_${st}
./sm_${max}_${st} ${max} ${st}

# Finish up
echo "Job Ended at `date`"
