#PBS -l nodes=1:ppn=4
#PBS -l walltime=1:00:00
#PBS -l pmem=2gb
#PBS -A open
#PBS -j oe
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load in module(s) 
module purge
module load python/3.3
module load gcc/5.3.1
module load parallel/20170522

# Go to the correct place
cd $PBS_O_WORKDIR
echo "loaded to the pwd"

# Run the job
parallel < para_tasks.txt
# Finish up
echo " "
echo "Job Ended at `date`"
echo " "
