#PBS -l nodes=1:ppn=2
#PBS -l walltime=3:00:00
#PBS -l pmem=2gb
#PBS -A open
#PBS -j oe
# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load in muscle 
module purge
module load gcc/5.3.1
module load muscle/3.8.31
echo "muscle is loaded"
# Go to the correct place
cd $PBS_O_WORKDIR
echo "loaded to the pwd"
# Run the job
muscle -in input.fa -out output.afa

# Finish up
echo " "
echo "Job Ended at `date`"
echo " "
