#!/bin/bash

#PBS -l nodes=3:ppn=4:stmem
#PBS -l pmem=1gb
#PBS -l walltime=20:00
#PBS -A wff3_b_g_sc_default
#PBS -N parj_test
#PBS -j oe

# load julia from rise swst
module use /gpfs/group/RISE/sw7/modules
module load intel impi mkl julia/1.7.0
echo "Modules loaded:"
module list

# resource info
export OMP_NUM_THREADS=$(( PBS_NUM_NODES * PBS_NUM_PPN ))
export JULIA_NUM_THREADS=$(( PBS_NUM_NODES * PBS_NUM_PPN ))
echo "nodes = $PBS_NUM_NODES, ppn = $PBS_NUM_PPN"
echo "OMP_NUM_THREADS = $OMP_NUM_THREADS, JULIA_NUM_THREADS = $JULIA_NUM_THREADS"

# Go to the correct place
cd $PBS_O_WORKDIR

# Run the job itself
julia parcheck.jl

# !! machine-file flag seemes unnecessary as long adding procs from within *.jl file  
#julia --machine-file ${PBS_NODEFILE} parcheck.jl
# !!

echo "Job ${PBS_JOBNAME} ended at `date`"
