#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00
#PBS -l pmem=1gb
#PBS -A open

# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load required modules 
module purge
module load intel
module load impi
module load lammps

# Go to the correct place
cd $PBS_O_WORKDIR

# Run the job itself
mpirun -np 1 lammps -in in.crack

# Finish up
echo " "
echo "Job Ended at `date`"
echo " "

