#!/bin/sh

#PBS -A wff3_g_g_lc_icds-training
#PBS -l nodes=1:ppn=1                # 1 core
#PBS -l pmem=4gb                     # 4 GB RAM per core
#PBS -l walltime=00:20:00            # 20 minutes
#PBS -j oe                           # Join output and error file

# Change to working directory
cd $PBS_O_WORKDIR

# *Need to call will go away*
module use /gpfs/group/RISE/sw7/modules

# Add MATLAB to system path
module load matlab/R2020b

# Run code
matlab -batch calc_pi_multi_node
