#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=2gb
#PBS -l walltime=10:00
#PBS -A open

# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load modules and set environment
module load schrodinger/2016.4
export SCHRODINGER_TMPDIR=/gpfs/scratch/jmp579
export SCHRODINGER_NODEFILE=$PBS_NODEFILE
NUMTASKS=`cat $PBS_NODEFILE | wc -l`
# cd to the submission directory
cd $PBS_O_WORKDIR

# Run maestro
#/opt/aci/sw/schrodinger/2016.4/glide glide-dock_SP_8.in -OVERWRITE -NJOBS 2 -HOST localhost:2 -WAIT -NONICE
/opt/aci/sw/schrodinger/2016.4/glide glide-dock_SP_8.in -OVERWRITE -NJOBS ${NUMTASKS} -WAIT -NONICE
