#!/bin/bash



# Administrative items
readonly SCRIPT=$(basename $0)
readonly AUTHOR="rkc10,jmp579"
readonly REVISION="1.0"
readonly DATE="2019-04-16"




##  (OPTIONAL) Put these 2 in your bashrc for easier calling access:
##export PATH=/gpfs/group/wff3/default/scripts:$PATH
##export PATH=/gpfs/group/wff3/default/scripts/openldap-2.4.47/bin/:$PATH

# Check arguments before continuing
if [ $# -gt 1 ]; then
   echo "Usage: ${SCRIPT} <userid> || ${SCRIPT}"
   echo ""
   echo "Author: ${AUTHOR}"
   echo "Date:   ${DATE}"
   echo ""
   exit 1
fi


name=${1}

if [ -z $name ]; then

echo -n "Enter client USERID and press [ENTER]: "
read name
fi


id $name>tmp[$name]
if grep -q "uid" tmp[$name]
then
export PATH=/gpfs/group/wff3/default/scripts/openldap-2.4.47/bin:$PATH
echo "You have done a Quota Check on: `ldapsearch -x -b dc=psu,dc=edu -h ldap.psu.edu uid=$name -LLL|grep displ|sed -e 's#.*: \(\)#\1#'`  (`ldapsearch -x -b dc=psu,dc=edu -h ldap.psu.edu uid=$name -LLL|grep eduPersonPrimaryAffiliation|sed -e 's#.*: \(\)#\1#'`)" 
echo \

cat /storage/home/.storagequotas/aciquotareport|grep -w $name|awk '{print "HOME >>      " $3/$5*100 "% or " $3/1048576 "GB  ""Inodes: " $9/$11*100"% or " $9"/"$11 }'
cat /storage/work/.storagequotas/aciquotareport|grep -w $name|awk '{print "WORK >>      " $3/$5*100 "% or " $3/1048576 "GB  "  "Inodes: " $9/$11*100"% or " $9"/"$11}'
cat /gpfs/scratch/.storagequotas/aciquotareport|grep -w $name|awk '{print "SCRATCH >>   " $3/1048576 "GB  " "Inodes: " $9/$11*100"% or " $9"/"$11}'
echo \

echo "$name has access to following: `id $name -Gn`"


echo \

else
        echo \ 
fi


rm -rf tmp[$name]
