#!/bin/bash

echo "hello, $USER. whose account do you want to check?"

echo -n "Enter client USERID and press [ENTER]: "
read name

sudo $(which mam-list-accounts) -u $name>tmp[$name]

if grep -q "open" tmp[$name]
then 
	echo "Yes, User $name has an active account "
	rm tmp[$name]
else 
	echo "No $name does not have an active ACI account"
##	exit 1
fi
