#!/bin/bash
##This script prints CyberLAMP GPU and Core utilization as reported by pbsnodes

# Administrative items
readonly SCRIPT=$(basename $0)
readonly AUTHOR="Justin Petucci <jmp579@psu.edu>"
readonly REVISION="1.0"
readonly DATE="2017-08-24"

# Check arguments before continuing
if [ $# -ne 0 ]; then
   echo "Usage: ${SCRIPT}; Prints free GPUs and Cores"
   echo ""
   echo "Author: ${AUTHOR}"
   echo "Date:   ${DATE}"
   echo ""
   exit 1
fi

#get node status from torque
pbsnodes > pbsnodesout

echo ${pbsnodesout}
#loop over all CL nodes
freegpusct=0
totalgpusct=0
echo "Current CyberLAMP GPU and Core utilization:"
echo " "
for i in {0001..0085}
do

#Count number of free GPUs and cores
numgpufree=`cat pbsnodesout | sed -n -e '/comp-clgc-'$i'/,/dedicated_threads/ p' | tr ';' '\n' | grep Unallocated | wc -l`
freegpusct=$((${freegpusct}+${numgpufree}))
numcpu=`cat pbsnodesout | sed -n -e '/comp-clgc-'$i'/,/dedicated_threads/ p' | tr ';' '\n' | grep total_threads | awk '{print $3}'`
numcoreused=`cat pbsnodesout | sed -n -e '/comp-clgc-'$i'/,/dedicated_threads/ p' | tr ';' '\n' | grep dedicated_threads | awk '{print $3}'`
numgpu=`cat pbsnodesout | sed -n -e '/comp-clgc-'$i'/,/dedicated_threads/ p' | tr ';' '\n' | grep gpu_state | wc -l`
totalgpusct=$((${totalgpusct}+${numgpu}))

if [ "$numgpufree" -ne "0"  ]; then
tput setaf 2; echo "comp-clgc-$i: GPUfree $numgpufree/${numgpu}: CORESused ${numcoreused}/${numcpu}"
else
tput setaf 1; echo "comp-clgc-$i: GPUfree $numgpufree/${numgpu}: CORESused ${numcoreused}/${numcpu}"
fi
done

##clean up and print totals
tput sgr0
echo "Total GPUSfree: ${freegpusct}/${totalgpusct}"
rm pbsnodesout
