#!/bin/sh

#PBS -A wff3_e_g_p100_default
#PBS -l nodes=1:ppn=20:gpus=1        # 20 cores (1 node), 1 GPU
#PBS -l pmem=4gb                     # 4 GB RAM per core
#PBS -l walltime=00:10:00            # 10 minutes
#PBS -j oe                           # Join output and error file

# Change to working directory
cd $PBS_O_WORKDIR

# *Need to call will go away*
module use /gpfs/group/RISE/sw7/modules

# Add MATLAB to system path
module load matlab/R2020b

# Run code
matlab -batch mandelbrot_example
