#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -l pmem=1gb
#PBS -A open
#PBS -j oe
# Get started
echo " "
echo "Job started on `hostname` at `date`"
echo " "

# Load in module 
module load oraclejdk 
echo "oraclejdk is loaded"
# Go to the correct place
cd $PBS_O_WORKDIR
echo "loaded to the pwd"
# Run the job
javac KMeans.java
java KMeans

# Finish up
echo " "
echo "Job Ended at `date`"
echo " "
